In [98]:
import os
import pandas as pd
import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from sklearn.preprocessing import LabelEncoder

In [99]:

# Load the CSV file
csv_file = "myntra_dataset.csv"  # Update with your CSV file path
data = pd.read_csv(csv_file)

# Display the first few rows of the dataset
print(data.head())

      filename  gender sleeve_length
0  Image_1.jpg  female   half_sleeve
1  Image_2.jpg  female   full_sleeve
2  Image_3.jpg  female   half_sleeve
3  Image_4.jpg  female   full_sleeve
4  Image_5.jpg    male   half_sleeve


In [100]:
data.shape

(20, 3)

In [101]:
# Preprocess images
data['filename'] = data['filename'].apply(lambda x: os.path.join('C:/Users/nidhi/Desktop/Myntra_cloth_images', x))
image_data = []
for filename in data["filename"]:
    img = load_img(filename, target_size=(224, 224))  # Assuming image size is 224x224
    img_array = img_to_array(img) / 255.0  # Normalize pixel values
    image_data.append(img_array)

In [102]:
# Preprocess labels
label_encoder = LabelEncoder()
data['gender'] = label_encoder.fit_transform(data['gender'])
data['sleeve_length'] = label_encoder.fit_transform(data['sleeve_length'])


In [112]:
# Convert data to numpy arrays
X = np.array(image_data)
y_gender = np.array(data['gender'])
y_sleeve_length = np.array(data['sleeve_length'])


In [104]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and validation sets
X_train, X_val, y_gender_train, y_gender_val, y_sleeve_length_train, y_sleeve_length_val = train_test_split(
    X, y_gender, y_sleeve_length, test_size=0.2, random_state=42)


In [119]:
y_sleeve_length_val

array([1, 1, 1, 0])

In [155]:
X_train,X_test,y_gender_train,y_gender_test=train_test_split(X,y_gender,test_size=0.3,random_state=0)

In [133]:
X_train.shape

(16, 224, 224, 3)

In [134]:
y_gender_train.shape

(16,)

In [146]:
X_train,X_test,y_sleeve_length_train,y_sleeve_length_test=train_test_split(X,y_sleeve_length,test_size=0.3,random_state=42)

In [149]:
X_train.shape

(16, 224, 224, 3)

In [150]:
X_test.shape

(4, 224, 224, 3)

In [151]:
y_sleeve_length_train.shape

(16,)

In [105]:
y_gender_train

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0])

In [106]:
X_train

array([[[[0.8       , 0.8       , 0.80784315],
         [0.7921569 , 0.7921569 , 0.8       ],
         [0.7764706 , 0.7764706 , 0.78431374],
         ...,
         [0.77254903, 0.7764706 , 0.79607844],
         [0.77254903, 0.7764706 , 0.79607844],
         [0.8       , 0.8039216 , 0.8235294 ]],

        [[0.76862746, 0.76862746, 0.7764706 ],
         [0.75686276, 0.75686276, 0.7647059 ],
         [0.7411765 , 0.7411765 , 0.7490196 ],
         ...,
         [0.73333335, 0.7372549 , 0.75686276],
         [0.73333335, 0.7372549 , 0.75686276],
         [0.7607843 , 0.7647059 , 0.78431374]],

        [[0.7764706 , 0.7764706 , 0.78431374],
         [0.7647059 , 0.7647059 , 0.77254903],
         [0.7529412 , 0.7529412 , 0.7607843 ],
         ...,
         [0.73333335, 0.7372549 , 0.75686276],
         [0.73333335, 0.7372549 , 0.75686276],
         [0.7607843 , 0.7647059 , 0.78431374]],

        ...,

        [[0.7137255 , 0.72156864, 0.7176471 ],
         [0.7019608 , 0.70980394, 0.7058824 ]

In [173]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# model = Sequential([
#     Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),
#     MaxPooling2D((2, 2)),
#     Conv2D(64, (3, 3), activation='relu'),
#     MaxPooling2D((2, 2)),
#     Conv2D(128, (3, 3), activation='relu'),
#     MaxPooling2D((2, 2)),
#     Flatten(),
#     Dense(128, activation='relu'),
#     Dense(1, activation='sigmoid')  # Binary classification for gender (male/female)
# ])
# num_classes = 4
# model = Sequential([
#     Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),
#     MaxPooling2D((2, 2)),
#     Conv2D(64, (3, 3), activation='relu'),
#     MaxPooling2D((2, 2)),
#     Conv2D(128, (3, 3), activation='relu'),
#     MaxPooling2D((2, 2)),
#     Flatten(),
#     Dense(128, activation='relu'),
#     Dense(1, activation='softmax')  # For multi-label classification
# ])
model1 = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(1, activation='softmax'),  # Output for gender (2 classes: male, female)
    Dense(1, activation='softmax')   # Output for sleeve length (2 classes: full_sleeve, half_sleeve)
])
model2 = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(1, activation='softmax'),  # Output for gender (2 classes: male, female)
    Dense(1, activation='softmax')
])
# model = Sequential([
#     Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),
#     MaxPooling2D((2, 2)),
#     Conv2D(64, (3, 3), activation='relu'),
#     MaxPooling2D((2, 2)),
#     Flatten(),
#     Dense(128, activation='relu'),
#     Dense(1, activation='softmax'),  # Output for gender (2 classes: male, female)
#        # Output for sleeve length (2 classes: full_sleeve, half_sleeve)
# ])

In [174]:
model1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [185]:
model1=model1.fit(X, y_gender, epochs=10)
# model1.fit(X, y_gender, epochs=10, validation_data=(X, y_gender))

Epoch 1/10
1/1 [==============================] - 4s 4s/step - loss: 0.7758 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 1s 963ms/step - loss: 0.7754 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 1s 972ms/step - loss: 0.7750 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 1s 990ms/step - loss: 0.7746 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 500ms/step - loss: 0.7742 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 1s 752ms/step - loss: 0.7738 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 1s 818ms/step - loss: 0.7735 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 1s 672ms/step - loss: 0.7731 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 1s 596ms/step - loss: 0.7727 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 1s 565ms/step - loss: 0.7723 - accuracy: 0.5500


In [186]:
model2=model2.fit(X, y_sleeve_length, epochs=10)

Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 1.2471 - accuracy: 0.6500
Epoch 2/10
1/1 [==============================] - 1s 954ms/step - loss: 1.2462 - accuracy: 0.6500
Epoch 3/10
1/1 [==============================] - 1s 995ms/step - loss: 1.2452 - accuracy: 0.6500
Epoch 4/10
1/1 [==============================] - 1s 710ms/step - loss: 1.2442 - accuracy: 0.6500
Epoch 5/10
1/1 [==============================] - 1s 964ms/step - loss: 1.2432 - accuracy: 0.6500
Epoch 6/10
1/1 [==============================] - 1s 810ms/step - loss: 1.2423 - accuracy: 0.6500
Epoch 7/10
1/1 [==============================] - 1s 683ms/step - loss: 1.2413 - accuracy: 0.6500
Epoch 8/10
1/1 [==============================] - 1s 700ms/step - loss: 1.2403 - accuracy: 0.6500
Epoch 9/10
1/1 [==============================] - 1s 670ms/step - loss: 1.2393 - accuracy: 0.6500
Epoch 10/10
1/1 [==============================] - 1s 601ms/step - loss: 1.2384 - accuracy: 0.6500


In [181]:
loss, accuracy = model1.evaluate(X, y_gender)
print("Accuracy:", accuracy)

1/1 [==============================] - 0s 137ms/step - loss: 0.7758 - accuracy: 0.5500
Accuracy: 0.550000011920929


In [166]:
predictions = model.predict(X_test)
predictions

1/1 [==============================] - 0s 106ms/step


array([[0.50386083],
       [0.50386083],
       [0.50386083],
       [0.50386083],
       [0.50386083],
       [0.50386083]], dtype=float32)

In [167]:
y_gender_test

array([0, 0, 0, 1, 1, 1])

In [113]:
model.save("myntra_classifier.h5")

In [114]:
from tensorflow.keras.models import load_model

model = load_model("myntra_classifier.h5")

In [170]:
data.gender.value_counts()

1    11
0     9
Name: gender, dtype: int64

In [171]:
data. sleeve_length.value_counts()


1    13
0     7
Name: sleeve_length, dtype: int64

In [187]:
import pickle

# Save the model to a file
with open('model1.pkl', 'wb') as f:
    pickle.dump(model1, f)
with open('model2.pkl', 'wb') as f:
    pickle.dump(model2, f) 

INFO:tensorflow:Assets written to: ram://5310f5ea-9a46-4dff-9a02-a5ea0fc3360c/assets


INFO:tensorflow:Assets written to: ram://5310f5ea-9a46-4dff-9a02-a5ea0fc3360c/assets


INFO:tensorflow:Assets written to: ram://ecf1c389-3e0d-487d-93b6-0197459c3618/assets


INFO:tensorflow:Assets written to: ram://ecf1c389-3e0d-487d-93b6-0197459c3618/assets
